WebApplication1/ViewModels/ImportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApplication1.Business.Logic.Import;
using WebApplication1.Migrations;

namespace WebApplication1.ViewModels
{
    public class ImportViewModel
    {
        public int NewLungers { get; set; }
        public int UppdatedLungers { get; set; }

        public int NewHorses { get; set; }
        public int UpdatedHorses { get; set; }

        public int NewClubs { get; set; }
        public int UpdatedClubs { get; set; }
        public int NewClasses { get; set; }
        public int UpdatedClasses { get; set; }

        public int NewTeams { get; set; }
        public int UpdatedTeams { get; set; }

        public int NewTeamMembers { get; set; }
        public int UpdatedTeamMembers { get; set; }

        public int NewVaulters { get; set; }
        public int UpdatedVaulters { get; set; }


        public Dictionary<int,Changed> ChangedStartListTeamList { get; set; }
        public Dictionary<int, UpdateService.NewHordeorders> ChangedStartListIndividualList { get; set; }



    }
}

WebApplication1/Controllers/ImportController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClosedXML.Excel;
using WebApplication1.Business.Logic.Import;
using WebApplication1.Controllers.DTO;
using WebApplication1.Models;
using WebApplication1.ViewModels;

namespace WebApplication1.Controllers
{
    public class ImportController : Controller
    {
        private RequestService _requestService;
        private UpdateService _updateService;

        public ImportController()
        {
            _requestService = new RequestService(Request);
            _updateService = new UpdateService();

        }



        // GET: Import
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(ImportViewModel model, HttpPostedFileBase file, string addNewCheckbox, string updateCheckbox, string excludeStartlist, string excludeTeam)
        {



            _requestService = new RequestService(Request);
            _updateService.AddNew = _requestService.IsCheckboxChecked(addNewCheckbox);
            _updateService.UpdateExisting = _requestService.IsCheckboxChecked(updateCheckbox);
            _updateService.ExcludeStartlist = _requestService.IsCheckboxChecked(excludeStartlist);
            _updateService.ExcludeTeam = _requestService.IsCheckboxChecked(excludeTeam);
            
            var workbook = _requestService.GetWorkbook(file);
            var excelImportService = new ExcelImportService(workbook);
            //var _updateService = new UpdateService();
            Changed changedItems;
            var lungers = excelImportService.GetLungers();
            changedItems = _updateService.UpdateLungers(lungers);

            model.NewLungers = changedItems.New;
            model.UppdatedLungers = changedItems.Updated;


            var horses = excelImportService.GetHorses();
            changedItems = _updateService.UpdateHorses(horses);
            model.NewHorses = changedItems.New;
            model.UpdatedHorses = changedItems.Updated;

            var clubs = excelImportService.GetClubs();
            changedItems = _updateService.UpdateClubs(clubs);
            model.NewClubs = changedItems.New;
            model.UpdatedClubs = changedItems.Updated;

            var classes = excelImportService.GetClasses();
            changedItems = _updateService.UpdateClasses(classes);
            model.NewClasses = changedItems.New;
            model.UpdatedClasses = changedItems.Updated;

            var vaulters = excelImportService.GetVaulters();
            changedItems = _updateService.UpdateVaulters(vaulters);
            model.NewVaulters = changedItems.New;
            model.UpdatedVaulters = changedItems.Updated;

            var startlistSteps = excelImportService.GetStartlistSteps();
            changedItems = _updateService.UpdateStartOrderSteps(startlistSteps);


            if (!_updateService.ExcludeTeam)
            {
                var teams = excelImportService.GetTeams();
                changedItems = _updateService.UpdateTeams(teams);
                model.NewTeams = changedItems.New;
                model.UpdatedTeams = changedItems.Updated;

                var teamMembers = excelImportService.GetTeamMembers();
                changedItems = _updateService.UpdateTeamMembers(teamMembers); //Observera att den inte tar bort teammembers. Bara lägger till eller ändrar ordning
                model.NewTeamMembers = changedItems.New;
                model.UpdatedTeamMembers = changedItems.Updated;
            }

            var horseOrders = excelImportService.GetTeamsHorseordersFromStartList();
            if (horseOrders != null) // om det finns en startlista i excelen
            {
                var horseOrdersTeams = horseOrders.Where(horseOrder => horseOrder.IsTeam).ToArray();
                var changed = _updateService.UpdateTeamHorseOrders(horseOrdersTeams);
                //changedItems = _updateService.UpdateTeams(teams.ToArray());
                //model.NewTeams = changedItems.New;
                //model.UpdatedTeams = changedItems.Updated;

                var horseOrdersIndividual = horseOrders.Where(horseOrder => !horseOrder.IsTeam).ToArray();
                var newHordeorders = _updateService.UpdateIndividualHorseOrders(horseOrdersIndividual);
                //changedItems = _updateService.UpdateTeams(teams.ToArray());
                //model.NewVaulters = newHordeorders.NewHorseOrders;
                //model.ne = newHordeorders;


                // 2. Hämta teammemebers. Kan nog göras på samma sätt som i GetTeamsFromStartList
                // 3. hämta individualla 
                // 4. importera HorseOrders

                //TODO: var teamMembers = excelImportService.GetTeamMembersFromStartList();
                //changedItems = _updateService.UpdateTeamMembers(teamMembers); 
                return View("Index", model);
            }


            if (!_updateService.ExcludeStartlist) // om  det inte finns en startlista i exceln
            {
                if (!_updateService.ExcludeTeam)
                {
                    var changedStartlist = ImportTeams(excelImportService);
                    model.ChangedStartListTeamList = changedStartlist;
                }

                var changedStartlistIndividual = ImportIndividuals(excelImportService);
                model.ChangedStartListIndividualList = changedStartlistIndividual;
            }

            return View("Index", model);
        }



        private Dictionary<int, Changed> ImportTeams(ExcelImportService excelImportService)
        {
            Dictionary<int, Changed> TeamsStartlistChanged = new Dictionary<int, Changed>();
  
        //    TeamsStartlistChanged = TeamOneDayTraHast(excelImportService, TeamsStartlistChanged);
            TeamsStartlistChanged = TeamOneDayCompetion(excelImportService, TeamsStartlistChanged);
        //   TeamsStartlistChanged = TeamSMCompetion(excelImportService, TeamsStartlistChanged);

            return TeamsStartlistChanged;
        }

        private Dictionary<int, Changed> TeamOneDayCompetion(ExcelImportService excelImportService, Dictionary<int, Changed> TeamsStartlistChanged)
        {
            var stepIdsWithClasses = excelImportService.GetStartlistStepCompetionClasses();
            return ImportTeam(excelImportService, TeamsStartlistChanged, stepIdsWithClasses);

            //var startListTdbClasses = new List<StartListTdbClasses>();

            ////var startListTdbClass = new StartListTdbClasses
            ////{
            ////    CompetitionClassesTdbIds = new[] { 618115,1 , 10},             //senior lag
            ////    StepMoment = new StepMoment[]
            ////    {
            ////        new StepMoment { StartListClassStepId = 18, TestNumber = 1 },
            ////        new StepMoment { StartListClassStepId = 7, TestNumber = 2 }
            ////    }
            ////};
            ////startListTdbClasses.Add(startListTdbClass);

            //var startListTdbClass = new StartListTdbClasses
            //{
            //    CompetitionClassesTdbIds = new[] { 630068 },            //Junior lag
            //    StepMoment = new StepMoment[]
            //    {
            //        new StepMoment { StartListClassStepId = 16, TestNumber = 1 },
            //        new StepMoment { StartListClassStepId = 10, TestNumber = 2 }
            //    }
            //};
            //startListTdbClasses.Add(startListTdbClass);

            ////startListTdbClass = new StartListTdbClasses
            ////{
            ////    CompetitionClassesTdbIds = new[] { 102, 103 },            //senior 2 star Pay and vault
            ////    StepMoment = new StepMoment[]
            ////    {
            ////        new StepMoment { StartListClassStepId = 3103, TestNumber = 1 },
            ////        new StepMoment { StartListClassStepId = 3103, TestNumber = 2 }
            ////    }
            ////};
            ////startListTdbClasses.Add(startListTdbClass);

            ////startListTdbClass = new StartListTdbClasses
            ////{
            ////    CompetitionClassesTdbIds = new[] { 100 },            //senior 2 star Pay and vault
            ////    StepMoment = new StepMoment[]
            ////    {
            ////        new StepMoment { StartListClassStepId = 3101, TestNumber = 1 },
            ////        new StepMoment { StartListClassStepId = 3103, TestNumber = 2 }
            ////    }
            ////};
            ////startListTdbClasses.Add(startListTdbClass);

            ////startListTdbClass = new StartListTdbClasses
            ////{
            ////    CompetitionClassesTdbIds = new[] { 568987 },            //Mellanklass lag
            ////    StepMoment = new StepMoment[]
            ////    {
            ////        new StepMoment { StartListClassStepId = 55, TestNumber = 1 },
            ////        new StepMoment { StartListClassStepId = 56, TestNumber = 2 }
            ////    }
            ////};
            ////startListTdbClasses.Add(startListTdbClass);


            //startListTdbClass = new StartListTdbClasses
            //{
            //    CompetitionClassesTdbIds = new[] { 630082 },  //Lättklass, lag typ 1
       
            //    StepMoment = new StepMoment[]
            //    {
            //        new StepMoment { StartListClassStepId = 40, TestNumber = 1 },
            //        new StepMoment { StartListClassStepId = 40, TestNumber = 2 },
            //    }
            //};
            //startListTdbClasses.Add(startListTdbClass);

            //startListTdbClass = new StartListTdbClasses
            //{
            //    CompetitionClassesTdbIds = new[] { 630083 },  //Skrittklass, lag typ 1

            //    StepMoment = new StepMoment[]
            //    {
            //        new StepMoment { StartListClassStepId = 43, TestNumber = 1 },

WebApplication1/Views/Import/Index.cshtml
@using WebApplication1.Business.Logic.Import
@model WebApplication1.ViewModels.ImportViewModel

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

@using (Html.BeginForm("Upload", "Import", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="File"  />
    <label for="AddNewCheckbox">Lägg till nya</label><input type="checkbox" name="addNewCheckbox" id="AddNewCheckbox" />
    <label for="UpdateCheckbox">Uppdatera redan existerande</label><input type="checkbox" name="updateCheckbox" id="UpdateCheckbox" />
    <label for="UpdateCheckbox">Gör ingen koll av startlistan </label><input type="checkbox" name="excludeStartlist" id="excludeStartlist" checked="checked" />
    <label for="excludeTeam">Updatera eller lägg inte till lag </label><input type="checkbox" name="excludeTeam" id="excludeTeam" checked="checked" />


    <input type="submit" name="Submit" id="Submit" value="Upload" />
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<div>
    <div>
        Nya longörer: @Html.DisplayFor(modelItem => modelItem.NewLungers) <br />
        Uppdaterade longörer: @Html.DisplayFor(modelItem => modelItem.UppdatedLungers)
    </div>
    <div>
        Nya hästar: @Html.DisplayFor(m => m.NewHorses) <br />
        Updaterade hästar: @Html.DisplayFor(m => m.UpdatedHorses)
    </div>
    <div>

        Nya klubbar: @Html.DisplayFor(m => m.NewClubs) <br />
        Updaterade klubbar:  @Html.DisplayFor(m => m.UpdatedClubs)
    </div>
    <div>

        Nya klasser: @Html.DisplayFor(m => m.NewClasses) <br />
        Updaterade klasser: @Html.DisplayFor(m => m.UpdatedClasses)
    </div>
    <div>

        Nya voltigörer: @Html.DisplayFor(m => m.NewVaulters) <br />
        Updaterade voltigörer: @Html.DisplayFor(m => m.UpdatedVaulters)
    </div>
    <div>

        Nya lag: @Html.DisplayFor(m => m.NewTeams) <br />
        Updaterade lag: @Html.DisplayFor(m => m.UpdatedTeams)
    </div>
    <div>

        Nya lagmedlemmar: @Html.DisplayFor(m => m.NewTeamMembers) <br />
        Updaterade lagmedlemmar: @Html.DisplayFor(m => m.UpdatedTeamMembers)
    </div>
    <div>

        @foreach (var item in Model?.ChangedStartListTeamList ?? new Dictionary<int, Changed>())
        {
            <div>
                <label>Startlisteklass</label>@Html.DisplayFor(m => item.Key) <br />
                <label>Ny startlista för lag</label>@Html.DisplayFor(m => item.Value.New) <br />
                <label>Ändrad startlista för lag</label>@Html.DisplayFor(m => item.Value.Updated)
            </div>
        }
    </div>
    <div>
        @foreach (var item in Model?.ChangedStartListIndividualList ?? new Dictionary<int, UpdateService.NewHordeorders>())
        {
            <div>
                <label>Startlisteklass</label>@Html.DisplayFor(m => item.Key) <br />
                <label>Ny startlista för häst</label>@Html.DisplayFor(m => item.Value.NewHorseOrders) <br />
                <label>Nya Individuell på häst</label>@Html.DisplayFor(m => item.Value.NewVaulterOrders)
            </div>
        }
    </div>


</div>